services:

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mosquitto_local
    ports:
      - "1883:1883"   # MQTT protocol
      - "9001:9001"   # (Optional) WebSocket support
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
